# Generated by Django 4.1.3 on 2023-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zips',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
